#!/usr/bin/env python3
"""
Setup script for Recipe Labs Lead Generator
One-command installation and configuration
"""

import os
import sys
import subprocess
from pathlib import Path

class SetupWizard:
    """Interactive setup wizard"""
    
    def __init__(self):
        self.project_dir = Path(__file__).parent
        self.env_file = self.project_dir / '.env'
    
    def run(self):
        """Run complete setup process"""
        print("\n" + "="*60)
        print("🚀 RECIPE LABS LEAD GENERATOR - SETUP WIZARD")
        print("="*60 + "\n")
        
        # Step 1: Check Python version
        self.check_python_version()
        
        # Step 2: Install dependencies
        self.install_dependencies()
        
        # Step 3: Setup environment variables
        self.setup_environment()
        
        # Step 4: Initialize database
        self.init_database()
        
        # Step 5: Test configuration
        self.test_config()
        
        # Step 6: Show next steps
        self.show_next_steps()
    
    def check_python_version(self):
        """Check Python version"""
        print("📋 Checking Python version...")
        
        if sys.version_info < (3, 8):
            print("❌ Python 3.8 or higher required")
            print(f"   Your version: {sys.version}")
            sys.exit(1)
        
        print(f"✅ Python {sys.version.split()[0]}")
    
    def install_dependencies(self):
        """Install Python dependencies"""
        print("\n📦 Installing dependencies...")
        
        try:
            subprocess.run(
                [sys.executable, "-m", "pip", "install", "-r", "requirements.txt"],
                check=True,
                capture_output=True
            )
            print("✅ Dependencies installed")
        except subprocess.CalledProcessError as e:
            print(f"❌ Failed to install dependencies: {e}")
            sys.exit(1)
    
    def setup_environment(self):
        """Setup environment variables"""
        print("\n🔑 Setting up API keys...")
        
        if self.env_file.exists():
            print("⚠️  .env file already exists")
            response = input("   Overwrite? (y/n): ").strip().lower()
            if response != 'y':
                print("   Skipping environment setup")
                return
        
        # Get API keys from user
        print("\n📝 Please enter your API keys:")
        print("   (Press Enter to skip and add later)")
        
        apify_token = input("\n🔹 Apify API Token: ").strip()
        if not apify_token:
            print("   ⚠️  Get your token at: https://console.apify.com/account/integrations")
        
        google_api_key = input("🔹 Google AI API Key: ").strip()
        if not google_api_key:
            print("   ⚠️  Get your key at: https://aistudio.google.com/app/apikey")
        
        # Create .env file
        env_content = f"""# Recipe Labs Lead Generator - Environment Variables
# Generated by setup.py

# Required API Keys
APIFY_API_TOKEN={apify_token or 'your_apify_token_here'}
GOOGLE_API_KEY={google_api_key or 'your_google_api_key_here'}

# Optional: CRM Integrations (uncomment to enable)
# HUBSPOT_API_KEY=
# SALESFORCE_USERNAME=
# SALESFORCE_PASSWORD=
# SALESFORCE_SECURITY_TOKEN=

# Optional: Email Services (uncomment to enable)
# SENDGRID_API_KEY=
# SENDGRID_FROM_EMAIL=
# SMTP_HOST=
# SMTP_PORT=587
# SMTP_USERNAME=
# SMTP_PASSWORD=
"""
        
        with open(self.env_file, 'w') as f:
            f.write(env_content)
        
        if apify_token and google_api_key:
            print("✅ Environment configured")
        else:
            print("⚠️  Environment file created, but you need to add your API keys")
            print(f"   Edit: {self.env_file}")
    
    def init_database(self):
        """Initialize database"""
        print("\n🗄️  Initializing database...")
        
        try:
            from database import Database
            db = Database()
            stats = db.get_stats()
            print(f"✅ Database initialized ({stats['total_leads']} existing leads)")
        except Exception as e:
            print(f"⚠️  Database initialization: {e}")
    
    def test_config(self):
        """Test configuration"""
        print("\n🧪 Testing configuration...")
        
        try:
            from config import validate_config
            validate_config()
            print("✅ Configuration valid")
        except Exception as e:
            print(f"⚠️  Configuration issue: {e}")
            print("   You can fix this later by editing .env file")
    
    def show_next_steps(self):
        """Show next steps to user"""
        print("\n" + "="*60)
        print("✅ SETUP COMPLETE!")
        print("="*60)
        
        print("\n🎯 NEXT STEPS:\n")
        
        # Check if API keys are set
        if not os.getenv('APIFY_API_TOKEN') or os.getenv('APIFY_API_TOKEN') == 'your_apify_token_here':
            print("1️⃣  Add your API keys to .env file:")
            print("   - Apify: https://console.apify.com/account/integrations")
            print("   - Google AI: https://aistudio.google.com/app/apikey")
            print()
        
        print("2️⃣  Generate your first leads:")
        print("   python lead_generator.py --search \"plumbing companies in Boston\" --limit 50")
        print()
        
        print("3️⃣  View your leads:")
        print("   python dashboard.py")
        print("   Open: http://localhost:5000")
        print()
        
        print("4️⃣  Export for outreach:")
        print("   python export_leads.py --status qualified --format email")
        print()
        
        print("📚 For detailed instructions, see:")
        print("   - QUICKSTART.md (step-by-step guide)")
        print("   - README.md (full documentation)")
        print("   - config.py (customization options)")
        
        print("\n" + "="*60)
        print("🚀 Ready to generate leads!")
        print("="*60 + "\n")


def main():
    """Run setup wizard"""
    wizard = SetupWizard()
    
    try:
        wizard.run()
    except KeyboardInterrupt:
        print("\n\n⏹️  Setup cancelled")
        sys.exit(0)
    except Exception as e:
        print(f"\n❌ Setup failed: {e}")
        sys.exit(1)


if __name__ == '__main__':
    main()
